In [1]:
from ultralytics import YOLO

In [ ]:
import wandb
from ultralytics import YOLO

def main():
   wandb.login()
   model = YOLO('yolov8n-seg.pt')
   results = model.train(
   data = r'C:\Users\Asus Rog Strix\Desktop\Multimodal\Dataset\data.yaml',
   imgsz=320,
   epochs=1000,
   batch=4,
   lr0=0.001,
   lrf=0.00001,
   cos_lr=True,
   project='Potate',
   name='Potate_Segment')

if __name__ == '__main__':
   main()

In [28]:
model = YOLO('best.pt')

In [2]:
import os

# Path to the directory containing the label files
label_directory = 'Segment_Dataset/train/labels'

# Iterate through all .txt files in the directory
for filename in os.listdir(label_directory):
    if filename.endswith('.txt'):
        file_path = os.path.join(label_directory, filename)
        
        # Open the file and modify its content
        with open(file_path, 'r') as file:
            lines = file.readlines()

        # Modify the first number of each line
        modified_lines = []
        for line in lines:
            parts = line.split()
            parts[0] = '1'  # Change the first number to 1
            modified_lines.append(' '.join(parts) + '\n')

        # Save the modified content back to the file
        with open(file_path, 'w') as file:
            file.writelines(modified_lines)

print("First number in each line has been changed to 1.")


First number in each line has been changed to 1.


In [ ]:
import numpy as np

# The list of segmentation labels (x and y coordinates)
segmentation = [
    0.34375, 0.5166015625, 0.333984375, 0.4853515625, 
    0.3154296875, 0.46484375, 0.2822265625, 0.44921875, 
    0.2275390625, 0.462890625, 0.212890625, 0.4794921875, 
    0.21484375, 0.5361328125, 0.2490234375, 0.55859375, 
    0.298828125, 0.5595703125, 0.33984375, 0.5361328125, 
    0.34375, 0.5166015625
]

# Convert the list into x and y coordinates
x_coords = segmentation[::2]
y_coords = segmentation[1::2]

# Calculate the bounding box
x_min = min(x_coords)
x_max = max(x_coords)
y_min = min(y_coords)
y_max = max(y_coords)

# Print the bounding box (left, top, right, bottom)
bounding_box = (x_min, y_min, x_max, y_max)
print(f"Bounding box: {bounding_box}")


Bounding box: (0.212890625, 0.44921875, 0.34375, 0.5595703125)


In [ ]:
i = r'C:\Users\Asus Rog Strix\Desktop\Multimodal\Potatoes Segmentation.v2i.yolov8\train\labels\-_3_jpg.rf.fdcb9ac26af7923cd3f052f053b69575.txt'
r = r'C:\Users\Asus Rog Strix\Desktop\Multimodal\Potatoes Segmentation.v2i.yolov8\train\images\-_3_jpg.rf.fdcb9ac26af7923cd3f052f053b69575.jpg'


In [ ]:
import cv2


In [ ]:
img = cv2.imread(r)

In [ ]:
cv2.imshow('img', img)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# The list of segmentation labels (x and y coordinates)
segmentation = [
    0.34375, 0.5166015625, 0.333984375, 0.4853515625, 
    0.3154296875, 0.46484375, 0.2822265625, 0.44921875, 
    0.2275390625, 0.462890625, 0.212890625, 0.4794921875, 
    0.21484375, 0.5361328125, 0.2490234375, 0.55859375, 
    0.298828125, 0.5595703125, 0.33984375, 0.5361328125, 
    0.34375, 0.5166015625
]

# Convert the list into x and y coordinates
x_coords = segmentation[::2]
y_coords = segmentation[1::2]

# Calculate the bounding box
x_min = min(x_coords)
x_max = max(x_coords)
y_min = min(y_coords)
y_max = max(y_coords)

boxx = img[y_min:y_max, x_min:x_max]

# Plot the image
fig, ax = plt.subplots()
ax.imshow(img)

# Create a rectangle to represent the bounding box
bbox = patches.Rectangle(
    (x_min * img.shape[1], y_min * img.shape[0]),  # Bottom-left corner (scaled)
    (x_max - x_min) * img.shape[1],               # Width (scaled)
    (y_max - y_min) * img.shape[0],               # Height (scaled)
    linewidth=2, edgecolor='r', facecolor='none'
)

# Add the bounding box to the plot
ax.add_patch(bbox)

# Show the plot
plt.show()


TypeError: slice indices must be integers or None or have an __index__ method

In [3]:
import os
import cv2
import numpy as np

# Paths to the image and label directories
image_directory = 'Segment_Dataset/train/images'
label_directory = 'Segment_Dataset/train/labels'
output_directory = 'Dataset_seg'


# Function to parse label files and return segmentation data
def parse_label(label_path):
    with open(label_path, 'r') as file:
        lines = file.readlines()
    boxes = []
    for line in lines:
        parts = list(map(float, line.split()))
        label = int(parts[0])
        coordinates = np.array(parts[1:]).reshape(-1, 2)
        boxes.append((label, coordinates))
    return boxes


In [35]:
parse_label(r'C:\Users\Asus Rog Strix\Desktop\Multimodal\Potatoes Segmentation.v2i.yolov8\train\labels\-_3_jpg.rf.fdcb9ac26af7923cd3f052f053b69575.txt')

[(0,
  array([[    0.34375,      0.5166],
         [    0.33398,     0.48535],
         [    0.31543,     0.46484],
         [    0.28223,     0.44922],
         [    0.22754,     0.46289],
         [    0.21289,     0.47949],
         [    0.21484,     0.53613],
         [    0.24902,     0.55859],
         [    0.29883,     0.55957],
         [    0.33984,     0.53613],
         [    0.34375,      0.5166]])),
 (0,
  array([[    0.40234,     0.42676],
         [    0.41797,     0.38184],
         [     0.4082,     0.34082],
         [    0.37012,     0.31836],
         [    0.34082,     0.32031],
         [    0.29199,      0.3418],
         [    0.26367,     0.38965],
         [    0.26367,     0.41895],
         [    0.27637,     0.44141],
         [    0.31348,     0.46094],
         [    0.34375,     0.46191],
         [    0.36035,     0.45898],
         [    0.40234,     0.42676]])),
 (0,
  array([[    0.38086,     0.27441],
         [    0.37891,     0.24316],
         [    0.3

In [4]:
# Function to process images and get bounding boxes
import cv2
import numpy as np
import os

def process_image(image_path, label_filename, label_path):
    # Read the input image
    image = cv2.imread(image_path)
    
    # Parse the label file to get the segmentation coordinates
    boxes = parse_label(label_path)  # Assuming `parse_label` returns the boxes with their coordinates

    # Initialize an array to store the output
    output_boxes = []
    output_masks = []

    # Get image dimensions
    xx = image.shape[1]  # Width of the original image
    yy = image.shape[0]  # Height of the original image
    counter = 0
    for box in boxes:
        label, coordinates = box
        
        # Extract the bounding box coordinates
        x_min, y_min = np.min(coordinates, axis=0)
        x_max, y_max = np.max(coordinates, axis=0)

        # Scale the normalized coordinates to image dimensions
        x_min = int(x_min * xx)
        y_min = int(y_min * yy)
        x_max = int(x_max * xx
                    )
        y_max = int(y_max * yy)

        # Create a cropped box image (bounding box area)
        boxxxx_img = image[y_min:y_max, x_min:x_max]

        # Now, we need to adjust the coordinates for the segmentation in the cropped image
        # Transform the segmentation coordinates into the new boxxxx_img coordinates
        cropped_width = boxxxx_img.shape[1]
        cropped_height = boxxxx_img.shape[0]
        
        # Adjust the coordinates of the segmentation
        new_coordinates = []
        for (x, y) in coordinates:
            new_x = int((x * xx) - x_min)  # Adjust the x-coordinate
            new_y = int((y * yy) - y_min)  # Adjust the y-coordinate
            new_coordinates.append((new_x/cropped_width, new_y/cropped_height))
        
        name = label_filename.split('.txt')[0]
        # Now, you can save the mask or process the segmentation as needed
        mask_filename = os.path.join('Dataset_seg/images', f'{name}_box_{counter}.jpg')
        cv2.imwrite(mask_filename, boxxxx_img)

        # Optionally, you can store the new coordinates for further processing
        output_boxes.append((label, new_coordinates))
        boxes_filename = os.path.join('Dataset_seg/labels', f'{name}_box_{counter}.txt')
        flattened_data = [0] + [item for coord in new_coordinates for item in coord]

        # Save the formatted data to a .txt file
        with open(boxes_filename, 'w') as f:
            f.write(" ".join(map(str, flattened_data)) + '\n')
        counter += 1

    return output_boxes, output_masks


In [5]:
# Iterate over all the images and labels
for image_filename in os.listdir(image_directory):
    if image_filename.endswith('.jpg') or image_filename.endswith('.png'):  # Ensure you process only image files
        image_path = os.path.join(image_directory, image_filename)
        label_filename = f"{os.path.splitext(image_filename)[0]}.txt"
        label_path = os.path.join(label_directory, label_filename)
       # print(image_path, '-----', label_filename, '-----------', label_path)
        # Process the image and label
        boxes, masks = process_image(image_path,label_filename, label_path)
print("Processing completed for all images.")


Processing completed for all images.


In [9]:
import glob

cc = glob.glob('Dataset_seg/images/*')

In [10]:
print(len(cc))

16448


In [11]:
import glob
from sklearn.model_selection import train_test_split

# Load the file paths of your images
cc = glob.glob('Dataset_seg/images/*')

# Split into train+valid and test sets (80% train+valid, 20% test)
train_valid, test = train_test_split(cc, test_size=0.2, random_state=42)

# Split train_valid into train and validation sets (80% train, 20% validation)
train, valid = train_test_split(train_valid, test_size=0.2, random_state=42)

# Now, train, valid, and test are your datasets
print(f"Train set size: {len(train)}")
print(f"Valid set size: {len(valid)}")
print(f"Test set size: {len(test)}")


Train set size: 10526
Valid set size: 2632
Test set size: 3290


In [13]:
# Save the paths into .txt files
with open('Dataset_seg/X_train.txt', "w") as f:
    for path in train:
        f.write(path + "\n")

with open('Dataset_seg/X_test.txt', "w") as f:
    for path in test:
        f.write(path + "\n")

with open('Dataset_seg/X_val.txt', "w") as f:
    for path in valid:
        f.write(path + "\n")

print("Files saved successfully.")

Files saved successfully.
